apiVersion: v1
kind: Service
metadata:
  name: mysql-transaction-db
spec:
  selector:
    app: mysql-transaction-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30003

  type: NodePort
