apiVersion: v1
kind: Service
metadata:
  name: mysql-user-db
spec:
  selector:
    app: mysql-user-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30004

  type: NodePort
