apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-expense-db
  labels:
    app: mysql-expense-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-expense-db
  template:
    metadata:
      labels:
        app: mysql-expense-db
    spec:
      containers:
        - name: mysql-expense-db
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "expense_db"
          ports:
            - containerPort: 3306
