apiVersion: v1
kind: Service
metadata:
  name: mysql-budget-db
spec:
  selector:
    app: mysql-budget-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001
  type: NodePort
