apiVersion: v1
kind: Service
metadata:
  name: transactions-service
spec:
  selector:
    app: transactions-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
